version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18   # You can change this to python, java, etc.
    commands:
      - echo Installing dependencies...
      - npm install
  pre_build:
    commands:
      - echo Running pre-build steps...
      - npm run lint
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Running tests...
      - npm test

artifacts:
  files:
    - '**/*'
  discard-paths: yes
